{
 "title": "Teranode Service Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "grouping_interval",
    "label": "Grouping Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(propagation_transactions_size_sum,instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "srvc", "label": "Service", "query": { "query": "label_values(service)" } },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Teranode Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processed Transaction by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(rate(teranode_propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container,namespace) >0)",
     "legendFormat": "Propagation - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_tx_blaster_processed_transactions{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by(namespace,)",
     "legendFormat": "Tx Blaster - {{ namespace }}"
    },
    {
     "expr": "sum(rate(teranode_blockassembly_add_tx_counter{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval]))  by (container,namespace)",
     "legendFormat": "Blockassembly - {{namespace}}"
    }
   ]
  },
  {
   "title": "TX Blaster Generated Transaction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_tx_blaster_workers{service=~\"tx-blaster-service.*\",namespace=~\"$namespace\"})",
     "legendFormat": "workers"
    },
    {
     "expr": "sum(rate(teranode_tx_blaster_processed_transactions{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (pod,namespace) > 0",
     "legendFormat": "Valid-{{pod}}-{{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_tx_blaster_invalid_transactions{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance,namespace) > 0",
     "legendFormat": "Invalid-{{instance}}-{{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_tx_blaster_retry_transactions{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance,namespace) > 0",
     "legendFormat": "Retries-{{instance}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Propagation Processed Transaction per Instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(rate(teranode_propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance,) >0)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(sum(rate(teranode_propagation_invalid_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance,) >0)",
     "legendFormat": "Invalid: {{instance}}"
    }
   ]
  },
  {
   "title": "Propagation Processed Transaction per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(rate(teranode_propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,) >0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines) by (namespace,container)",
     "legendFormat": "{{namespace}}: {{container}}"
    }
   ]
  },
  {
   "title": "Transactions Added by Block Assembly /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_blockassembly_add_tx_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container,namespace)",
     "legendFormat": "Transactions-{{container}}-{{namespace}}"
    },
    {
     "expr": "sum(teranode_subtreeprocessor_dynamic_subtree_size{service=~\"$srvc\",namespace=~\"$namespace\"}) by (container,namespace)",
     "legendFormat": "Subtree-Size-{{container}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "In Block Assembly",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(teranode_blockassembly_transactions{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (container,namespace) >0)",
     "legendFormat": "Transactions-{{namespace}}"
    },
    {
     "expr": "(sum(teranode_blockassembly_queued_transactions{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (container,namespace) >0)",
     "legendFormat": "Queued-{{namespace}}"
    },
    {
     "expr": "(sum(teranode_blockassembly_subtrees{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (container,namespace) >0)",
     "legendFormat": "Subtrees-{{namespace}}"
    }
   ]
  },
  {
   "title": "Transactions generated /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_validator_send_to_block_assembly_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container,namespace) > 0",
     "legendFormat": "Txs validator -> block-ass/{{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_validator_send_to_blockvalidation_kafka_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container,namespace) > 0",
     "legendFormat": "Tx Meta validator->block-val via kafka/ {{namespace}}"
    }
   ]
  },
  {
   "title": "Tx Meta read from Kafka /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreevalidation_set_tx_meta_cache_kafka_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container,instance) / 60 > 0",
     "legendFormat": "{{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Blaster workers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_tx_blaster_workers{namespace=~\"$namespace\"})by (instance,)   >0",
     "legendFormat": "Workers-{{instance}}"
    },
    {
     "expr": "sum(teranode_tx_blaster_worker_errors{namespace=~\"$namespace\"}) by (instance,)  >0",
     "legendFormat": "Worker errors - {{instance}}"
    }
   ]
  },
  {
   "title": "Queued Blocks in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_blockvalidation_block_found_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}) by (container,namespace)",
     "legendFormat": "Blocks queued-{{container}}-{{namespace}}"
    },
    {
     "expr": "sum(teranode_blockvalidation_catchup_count{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}) by (container,namespace)",
     "legendFormat": "Blocks catchup-{{container}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Subtrees processed by Subtree Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreevalidation_validate_subtree_count{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container) / 60",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Size of Catchup Channel in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_blockvalidation_catchup_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}) by (container)",
     "legendFormat": "Blocks catchup-{{container}}"
    }
   ]
  },
  {
   "title": "Subtrees processed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreevalidation_validate_subtree_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container) >0",
     "legendFormat": "Count: {{container}}"
    },
    {
     "expr": "sum(increase(teranode_subtreevalidation_validate_subtree_duration_sum{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container) >0",
     "legendFormat": "Duration: {{container}}"
    }
   ]
  },
  {
   "title": "Block Chain Mined Block",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "sum(increase(teranode_blockchain_add_block_count{service=~\"$srvc\",namespace=~\"$namespace\"}[1m])) by (container) >0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Aerospike UTXO",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_aerospike_utxo_create_batch_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "UTXO: Batch Create - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_aerospike_utxo_store{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "UTXO: Store - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_aerospike_utxo_spend_batch_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "UTXO: Spend Batch - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_aerospike_map_utxo_reset{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Map: Restore - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_aerospike_map_utxo_spend{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Map: Spend - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_aerospike_map_utxo_respend{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Map: Respend - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_aerospike_map_utxo_reset{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Map: Reset - {{namespace}}"
    }
   ]
  },
  {
   "title": "Aerospike Tx Meta",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_aerospike_txmeta_set_mined_batch_n{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Set-Mined-Batch - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_aerospike_txmeta_get_multi_n{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Get-Multi-BatchN - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_aerospike_txmeta_set_mined_batch_err_n{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Set-Multi-ErrN - {{namespace}}"
    }
   ]
  },
  {
   "title": "Aerospike MAP UTXO",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_aerospike_utxo_get[$grouping_interval])) / 60",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_store[$grouping_interval])) / 60",
     "legendFormat": "Store"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_store_spent[$grouping_interval])) / 60",
     "legendFormat": "Spent"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_restore[$grouping_interval])) / 60",
     "legendFormat": "Restore"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_spend[$grouping_interval])) / 60",
     "legendFormat": "Spend"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_respend[$grouping_interval])) / 60",
     "legendFormat": "Respend"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_spend_spent[$grouping_interval])) / 60",
     "legendFormat": "Spend Spent"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_reset[$grouping_interval])) / 60",
     "legendFormat": "Reset"
    }
   ]
  },
  {
   "title": "Aerospike MAP Tx Meta",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_aerospike_txmeta_get{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Get - {{namespace}}"
    },
    {
     "expr": "sum(rate(aerospike_map_txmeta_store{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Set - {{namespace}}"
    },
    {
     "expr": "sum(rate(aerospike_map_txmeta_delete{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Delete - {{namespace}}"
    },
    {
     "expr": "sum(rate(aerospike_map_txmeta_set_mined{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Set-Mined - {{namespace}}"
    },
    {
     "expr": "sum(rate(aerospike_map_txmeta_set_mined_batch{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Set-Mined-Batch - {{namespace}}"
    },
    {
     "expr": "sum(rate(aerospike_map_txmeta_set_mined_batch_n{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Set-Mined-BatchN - {{namespace}}"
    },
    {
     "expr": "sum(rate(aerospike_map_txmeta_get_multi_n{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Get-Multi-BatchN - {{namespace}}"
    },
    {
     "expr": "sum(rate(aerospike_map_txmeta_set_mined_batch_err_n{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Set-Multi-ErrN - {{namespace}}"
    },
    {
     "expr": "sum(rate(aerospike_map_utxo_respend{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Respends - {{namespace}}"
    }
   ]
  },
  {
   "title": "Tx Meta Cache in Subtree Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_tx_meta_cache_insertions{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container,instance) > 0 ",
     "legendFormat": "Cache insertions - {{container}} - {{instance}} rate"
    },
    {
     "expr": "sum(rate(teranode_blockvalidation_tx_meta_cache_hits{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (container,instance) > 0",
     "legendFormat": "Cache hits - {{container}} - {{instance}} rate"
    },
    {
     "expr": "sum(rate(teranode_blockvalidation_tx_meta_cache_misses{service!~\"tx-blaster.*\",service=~\"$srvc\"}[$grouping_interval])) by (container,instance) > 0",
     "legendFormat": "Cache misses - {{container}} - {{instance}} rate"
    },
    {
     "expr": "sum(rate(teranode_blockvalidation_tx_meta_cache_evictions{service!~\"tx-blaster.*\",service=~\"$srvc\"}[$grouping_interval])) by (container,instance) > 0",
     "legendFormat": "Cache evictions - {{container}} - {{instance}} rate"
    },
    {
     "expr": "sum(rate(teranode_blockvalidation_tx_meta_cache_get_origin{service!~\"tx-blaster.*\",service=~\"$srvc\"}[$grouping_interval])) by (container,instance) > 0 ",
     "legendFormat": "Get from Aeropsike - {{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Meta Cache Size in Subtree Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_tx_meta_cache_size{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (container,instance)\n",
     "legendFormat": "Cache size - {{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Queued Subtrees in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_blockvalidation_subtree_exists_cache{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (container, namespace)",
     "legendFormat": "Subtrees queued - {{container}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Tx Meta Cache Number of Elements Added In Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_tx_meta_cache_total_elements_added{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"})by (container,instance)",
     "legendFormat": "Cache size - {{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Asset Service - HTTP Get Subtrees",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_asset_http_get_subtree{namespace=~\"$namespace\"}[$grouping_interval])) by (pod,namespace)",
     "legendFormat": "{{pod}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Queued Blocks in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_blockvalidation_block_found_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "Blocks queued - {{ namespace}}"
    },
    {
     "expr": "sum(teranode_blockvalidation_last_validated_blocks_cache{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "Blocks in RAM - {{ namespace}}"
    }
   ]
  },
  {
   "title": "TX Blaster Errors",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_tx_blaster_internal_server_errors{service=~\"$service\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Internal Errors - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_tx_blaster_invalid_transactions{service=~\"$service\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Invalid Transactinos - {{namespace}}"
    },
    {
     "expr": "sum(rate(teranode_tx_blaster_tx_locked_retries_total{service=~\"$service\",namespace=~\"$namespace\"}[$grouping_interval])) by (namespace,)",
     "legendFormat": "Locked Transactinos - {{namespace}}"
    }
   ]
  },
  {
   "title": "Teranode Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator TX 2Phase Commit Latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 373 },
     "targets": [
      {
       "expr": "sum by (le) (rate(teranode_validator_transactions_2phase_commit_bucket[$grouping_interval]))",
       "legendFormat": "{{ le }}${latencytimeunit}"
      }
     ]
    },
    {
     "title": "Validator TX Create Latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 382 },
     "targets": [
      {
       "expr": "sum by (le) (rate(teranode_validator_set_tx_meta_bucket[$grouping_interval]))",
       "legendFormat": "{{ le }}${latencytimeunit}"
      }
     ]
    },
    {
     "title": "Validator TX Spend Latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 391 },
     "targets": [
      {
       "expr": "sum by (le) (rate(teranode_validator_transactions_spend_utxos_bucket[$grouping_interval]))",
       "legendFormat": "{{ le }}${latencytimeunit}"
      }
     ]
    },
    {
     "title": "Validator Send to BlockAss Latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 400 },
     "targets": [
      {
       "expr": "sum by (le) (rate(teranode_validator_send_to_block_assembly_bucket[$grouping_interval]))",
       "legendFormat": "{{ le }}${latencytimeunit}"
      }
     ]
    },
    {
     "title": "Propagation Processing Batch TX Latency ",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 409 },
     "targets": [
      {
       "expr": "sum by (le) (rate(teranode_propagation_transactions_batch_bucket[$grouping_interval]))",
       "legendFormat": "{{ le }}${latencytimeunit}"
      }
     ]
    }
   ]
  }
 ]
}