package settings

import "net/url"

// AlertSettings configures the alert notification service.
type AlertSettings struct {
	GenesisKeys   []string `key:"alert_genesis_keys" desc:"Genesis public keys for alert verification" default:"" category:"Alert" usage:"Keys that can sign alerts" type:"[]string" longdesc:"### Purpose\nDefines the list of genesis public keys authorized to sign alert messages on the Bitcoin SV network. Alert messages signed with these keys are considered authoritative network-wide announcements.\n\n### Use Cases\n- Critical security advisories\n- Protocol upgrade notices\n- Emergency communications\n\n### Format\nKeys in **hexadecimal format**, separated by |.\n\n### How It Works\n- Only messages signed by these keys will be processed and relayed\n- Empty list disables genesis alert verification\n\n### Recommendations\n- Production nodes should include official BSV alert keys for network security notices\n- Test networks may use custom keys for isolated alert testing"`
	P2PPrivateKey string   `key:"alert_p2p_private_key" desc:"P2P private key for alert service" default:"" category:"Alert" usage:"Identity key for P2P network" type:"string" longdesc:"### Purpose\nProvides the **Ed25519** or **secp256k1** private key for alert service P2P network identity, used to authenticate this node on the alert P2P network and sign outgoing alert messages (if this node is an alert originator).\n\n### Format\nHex-encoded private key.\n\n### Values\n- **Empty** - Auto-generation of ephemeral identity\n- **Set value** - Persistent identity across restarts\n\n### How It Works\nIf this node is authorized to create alerts, the key must match a key in GenesisKeys. Regular nodes use this only for P2P authentication.\n\n### Recommendations\n- Use persistent keys for alert originator nodes\n- Ephemeral keys are acceptable for regular relay nodes"`
	ProtocolID    string   `key:"alert_protocol_id" desc:"Protocol ID for alert P2P network" default:"/bitcoin/alert-system/1.0.0" category:"Alert" usage:"Identifies alert protocol version" type:"string" longdesc:"### Purpose\nSpecifies the **LibP2P protocol identifier** for the Bitcoin alert system P2P network, determining which peers can communicate.\n\n### How It Works\nNodes only communicate with peers supporting the same protocol ID. Version number indicates protocol compatibility - nodes with different versions may not interoperate.\n\n### Values\n- **/bitcoin/alert-system/1.0.0** (default) - Standard BSV alert network\n- Custom values for isolated test networks\n\n### Recommendations\n- Use the default for production nodes on the main BSV network\n- Change only if running an isolated alert network for testing"`
	StoreURL      *url.URL `key:"alert_store" desc:"Storage URL for alert data (parsed)" default:"sqlite:///alert" category:"Alert" usage:"Parsed URL for alert storage" type:"url" longdesc:"### Purpose\nProvides the parsed URL form of the alert_store setting for programmatic access to storage configuration components.\n\n### How It Works\nThis is the same value as alert_store but pre-parsed into URL components (scheme, host, path, credentials) for use by the alert service during storage backend initialization.\n\n### Recommendations\n- Configure via **alert_store** setting; this field is derived automatically\n- Use for programmatic access to individual URL components"`
	TopicName     string   `key:"alert_topic_name" desc:"P2P topic name for alerts" default:"bitcoin_alert_system" category:"Alert" usage:"PubSub topic for alert distribution" type:"string" longdesc:"### Purpose\nSpecifies the **LibP2P PubSub topic name** for distributing alert messages across the P2P network.\n\n### How It Works\n- All nodes subscribe to this topic to receive alerts\n- Nodes only see alerts published to topics they subscribe to\n- Topic names are **case-sensitive**\n\n### Values\n- **bitcoin_alert_system** (default) - Standard BSV alert network topic\n- Custom values for isolated test networks\n\n### Recommendations\n- Use the default for production nodes\n- Change only for isolated test networks to avoid cross-contamination"`
	P2PPort       int      `key:"ALERT_P2P_PORT" desc:"P2P port for alert service" default:"9908" category:"Alert" usage:"Port for alert P2P connections" type:"int" longdesc:"### Purpose\nSpecifies the TCP port for alert service P2P network connections, running on a **separate P2P network** from main Teranode P2P for isolation.\n\n### How It Works\n- Alert P2P operates independently from the main Teranode P2P network\n- Default port 9908 is chosen to avoid conflict with main P2P port (9906)\n- All alert network peers must be able to reach this port\n\n### Values\n- **9908** (default) - Standard alert P2P port\n- Custom port if 9908 conflicts with other services\n\n### Recommendations\n- Ensure firewall allows inbound/outbound TCP on this port\n- In containerized deployments, map to host port for external connectivity"`
}
