package settings

import (
	"net/url"
	"time"
)

// BlockChainSettings configures the blockchain state management service.
type BlockChainSettings struct {
	GRPCAddress           string            `key:"blockchain_grpcAddress" desc:"gRPC address for Blockchain service" default:"localhost:8087" category:"BlockChain" usage:"Address for inter-service communication" type:"string" longdesc:"### Purpose\nSpecifies the client connection address for the Blockchain gRPC service.\n\n### How It Works\nOther services connect to this address to query blockchain state, headers, and chain information.\n\n### Used By\n- **Block Validation** - Get headers, check chain\n- **Block Assembly** - Get best block\n- **Asset Server** - Query blocks\n- **RPC** - getblock, getblockheader\n\n### Format\n**host:port** - Where host is a hostname, IP address, or DNS name.\n\n### Examples\n- **localhost:8087** - Local development (default)\n- **blockchain.internal:8087** - Internal DNS\n- **10.0.1.50:8087** - Direct IP address\n\n### Recommendations\n- Use internal DNS or service mesh addresses in production\n- Use localhost only for local development"`
	GRPCListenAddress     string            `key:"blockchain_grpcListenAddress" desc:"gRPC listen address for Blockchain service" default:":8087" category:"BlockChain" usage:"Port for incoming gRPC connections" type:"string" longdesc:"### Purpose\nSpecifies the server binding address for the Blockchain gRPC service.\n\n### How It Works\nThis is the central service that all other services connect to for chain state. The blockchain service binds to this address to accept incoming gRPC connections.\n\n### Format\n- **:port** - Binds to all network interfaces\n- **ip:port** - Binds to a specific interface\n\n### Examples\n- **:8087** - Listen on all interfaces (default)\n- **127.0.0.1:8087** - Listen only on localhost\n- **10.0.1.50:8087** - Listen on specific interface\n\n### Recommendations\n- Use **:port** format for containerized deployments\n- Bind to specific IP for security in multi-tenant environments"`
	HTTPListenAddress     string            `key:"blockchain_httpListenAddress" desc:"HTTP listen address for Blockchain service" default:":8082" category:"BlockChain" usage:"Port for HTTP connections" type:"string" longdesc:"### Purpose\nSpecifies the HTTP listen address for blockchain service REST API endpoints.\n\n### How It Works\nProvides HTTP alternatives to gRPC for simple queries and health checks. The dashboard and monitoring tools use this endpoint.\n\n### Format\n- **:port** - Binds to all network interfaces\n- **ip:port** - Binds to a specific interface\n\n### Examples\n- **:8082** - Listen on all interfaces (default)\n- **127.0.0.1:8082** - Listen only on localhost\n\n### Recommendations\n- Use **:port** format for containerized deployments\n- Bind to specific IP for security in multi-tenant environments"`
	MaxRetries            int               `key:"blockchain_maxRetries" desc:"Maximum retry attempts for blockchain operations" default:"3" category:"BlockChain" usage:"Retries on transient failures" type:"int" longdesc:"### Purpose\nControls how many times blockchain database operations will retry on transient failures.\n\n### How It Works\n- Applies to transient failures like database timeouts, connection issues, and recoverable errors\n- Permanent errors (constraint violations, data corruption) fail immediately without retry\n- Each retry adds latency but improves reliability\n\n### Recommendations\n- **3** (default) - Provides reasonable reliability for most environments\n- Lower values for faster failure detection in stable environments\n- Higher values for unreliable database connections"`
	RetrySleep            int               `key:"blockchain_retrySleep" desc:"Sleep between retries in milliseconds" default:"1000" category:"BlockChain" usage:"Backoff between retry attempts" type:"int" longdesc:"### Purpose\nSets the wait time in milliseconds between blockchain operation retry attempts.\n\n### How It Works\nAfter a transient failure, the service waits this duration before attempting again, allowing temporary issues to resolve. Works with MaxRetries to determine total retry window.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter | Faster recovery | Higher database load during outages |\n| Longer | Reduced database load | Slower recovery |\n\n### Recommendations\n- **1000** (default, 1 second) - Good balance for most environments\n- Increase for databases with longer recovery times"`
	StoreURL              *url.URL          `key:"blockchain_store" desc:"Database URL for blockchain state" default:"sqlite:///blockchain" category:"BlockChain" usage:"Where chain state is persisted" type:"url" longdesc:"### Purpose\nSpecifies the database URL for blockchain state storage.\n\n### How It Works\nThe blockchain service persists critical chain data to this database, including block headers, chain tips, fork information, and FSM state.\n\n### Format\n| Database | URL Format |\n|----------|------------|\n| SQLite | sqlite:///path |\n| PostgreSQL | postgres://user:pass@host/db |\n\n### Examples\n- **sqlite:///blockchain** - Local SQLite file (default)\n- **postgres://user:pass@localhost:5432/blockchain** - PostgreSQL database\n\n### Recommendations\n- **Development**: Default sqlite:///blockchain is suitable\n- **Production**: Use PostgreSQL for reliability and concurrent access\n- Ensure backup strategy is in place for this critical data"`
	FSMStateRestore       bool              `key:"fsm_state_restore" desc:"Restore FSM state on startup" default:"false" category:"BlockChain" usage:"Resume from saved state" type:"bool" longdesc:"### Purpose\n**UNUSED** - This setting is currently not functional. The implementation that sent a Restore event via the RPC service is disabled.\n\n### How It Works\nThe FSM tracks node operational state (IDLE, RUNNING, CATCHINGBLOCKS, LEGACYSYNCING). This setting was intended to restore the previous FSM state from the database on startup, but the implementation is currently disabled.\n\n### Values\n- **false** (default) - No effect (setting is unused)\n- **true** - No effect (setting is unused)\n\n### Note\nOn startup, the blockchain service always restores the last persisted FSM state from its database store regardless of this setting."`
	FSMStateChangeDelay   time.Duration     `key:"fsm_state_change_delay" desc:"Delay between FSM state changes" default:"0" category:"BlockChain" usage:"Debounce state transitions" type:"duration" longdesc:"### Purpose\nSets the minimum delay before FSM state transitions take effect.\n\n### How It Works\nAdds a debounce delay to FSM state changes, preventing rapid transitions during startup or chain reorgs and reducing UI flicker in the dashboard.\n\n### Format\nGo duration string (e.g., 500ms, 1s, 2s).\n\n### Recommendations\n- **0** (default) - Immediate transitions for most deployments\n- Set to 500ms-1s to debounce rapid state changes if UI flicker is an issue"`
	StoreDBTimeoutMillis  int               `key:"blockchain_store_dbTimeoutMillis" desc:"Database operation timeout" default:"5000" category:"BlockChain" usage:"Maximum wait for DB operations" type:"int" longdesc:"### Purpose\nSets the timeout in milliseconds for blockchain database operations.\n\n### How It Works\nDatabase queries that exceed this timeout are cancelled and trigger retry logic if retries remain. This prevents operations from hanging indefinitely.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Higher | Tolerates slow queries | Slower failure detection |\n| Lower | Faster failure detection | May timeout valid slow queries |\n\n### Recommendations\n- **5000** (default, 5 seconds) - Suitable for most queries\n- Increase for slow databases or complex queries\n- Decrease for faster failure detection in high-performance environments"`
	InitializeNodeInState string            `key:"blockchain_initializeNodeInState" desc:"Initial FSM state for node" default:"" category:"BlockChain" usage:"Override startup state" type:"string" longdesc:"### Purpose\n**UNUSED** - This setting is defined but not referenced anywhere in the codebase.\n\n### How It Works\nThis setting was intended to force the blockchain service to initialize in a specific FSM state (IDLE, RUNNING, CATCHINGBLOCKS, LEGACYSYNCING) instead of using default initialization logic, but it is not currently implemented.\n\n### Values\n- **Empty string** (default) - No effect (setting is unused)\n\n### Note\nThe initial FSM state can be set via the -localTestStartFromState CLI argument instead."`
	PostgresPool          *PostgresSettings `key:"blockchain_postgres_pool" desc:"PostgreSQL connection pool settings" category:"BlockChain" usage:"Database connection pooling" type:"*PostgresSettings" longdesc:"### Purpose\nConfigures the connection pool for PostgreSQL blockchain store.\n\n### How It Works\nControls database connection pooling behavior including pool size, connection lifetime, and idle behavior. Proper tuning is critical for high-throughput deployments.\n\n### Recommendations\n- See PostgresSettings for individual parameter documentation\n- Tune pool size based on expected concurrent database operations\n- Monitor connection usage to optimize settings"`
	UseInMemoryChainCheck bool              `key:"blockchain_use_in_memory_chain_check" desc:"Use in-memory off-chain set for CheckBlockIsInCurrentChain instead of SQL recursive CTE" default:"false" category:"BlockChain" usage:"Toggle between in-memory and SQL chain membership checks" type:"bool" longdesc:"### Purpose\nControls whether CheckBlockIsInCurrentChain uses the in-memory off-chain set (fast O(1) lookup) or the original SQL recursive CTE (slower but proven).\n\n### Values\n- **true** - Use in-memory off-chain set with background refresh\n- **false** (default) - Use original SQL recursive CTE query\n\n### Recommendations\n- **true** for production deployments after validation\n- **false** to revert to proven SQL behavior if issues arise"`
	HeartbeatInterval     time.Duration     `key:"blockchain_heartbeat_interval" desc:"Interval for server heartbeat broadcasts" default:"10s" category:"BlockChain" usage:"Server PING broadcast frequency and client staleness detection" type:"duration" longdesc:"### Purpose\nControls how frequently the blockchain service broadcasts PING heartbeat notifications to all subscribers.\n\n### How It Works\nThe blockchain server periodically sends PING notifications to all connected clients (propagation, block assembly, etc.) to maintain subscription health. Clients automatically detect stale connections using a timeout of **3 × this interval**, allowing for up to 3 missed heartbeats before triggering reconnection.\n\n### Server Behavior\n- Broadcasts PING notifications at this interval to all subscribers\n- Logged at startup with configured value\n\n### Client Behavior\n- Tracks timestamp of last received PING\n- Considers subscription stale if no heartbeat received within **3 × interval**\n- Automatically sets FSM state to IDLE when stale, triggering reconnection\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter (5s) | Faster failure detection | Higher network overhead |\n| Longer (30s-60s) | Lower overhead | Slower failure detection |\n\n### Format\nGo duration string (e.g., 5s, 10s, 30s).\n\n### Examples\n- **10s** (default) - Server sends every 10s, clients timeout after 30s (3 missed)\n- **5s** - Server sends every 5s, clients timeout after 15s (3 missed)\n- **30s** - Server sends every 30s, clients timeout after 90s (3 missed)\n\n### Recommendations\n- **10s** (default) - Good balance for most deployments\n- Increase to 30s-60s in stable, low-latency networks to reduce overhead\n- Decrease to 5s for faster failure detection in unreliable networks\n- Single setting ensures server and client are always synchronized"`
}
