package settings

import (
	"net/url"
	"time"
)

// BlockChainSettings configures the blockchain state management service.
type BlockChainSettings struct {
	GRPCAddress           string            `key:"blockchain_grpcAddress" desc:"gRPC address for Blockchain service" default:"localhost:8087" category:"BlockChain" usage:"Address for inter-service communication" type:"string" longdesc:"### Purpose\nSpecifies the client connection address for the Blockchain gRPC service.\n\n### How It Works\nOther services connect to this address to query blockchain state, headers, and chain information.\n\n### Used By\n- **Block Validation** - Get headers, check chain\n- **Block Assembly** - Get best block\n- **Asset Server** - Query blocks\n- **RPC** - getblock, getblockheader\n\n### Format\n**host:port** - Where host is a hostname, IP address, or DNS name.\n\n### Examples\n- **localhost:8087** - Local development (default)\n- **blockchain.internal:8087** - Internal DNS\n- **10.0.1.50:8087** - Direct IP address\n\n### Recommendations\n- Use internal DNS or service mesh addresses in production\n- Use localhost only for local development"`
	GRPCListenAddress     string            `key:"blockchain_grpcListenAddress" desc:"gRPC listen address for Blockchain service" default:":8087" category:"BlockChain" usage:"Port for incoming gRPC connections" type:"string" longdesc:"### Purpose\nSpecifies the server binding address for the Blockchain gRPC service.\n\n### How It Works\nThis is the central service that all other services connect to for chain state. The blockchain service binds to this address to accept incoming gRPC connections.\n\n### Format\n- **:port** - Binds to all network interfaces\n- **ip:port** - Binds to a specific interface\n\n### Examples\n- **:8087** - Listen on all interfaces (default)\n- **127.0.0.1:8087** - Listen only on localhost\n- **10.0.1.50:8087** - Listen on specific interface\n\n### Recommendations\n- Use **:port** format for containerized deployments\n- Bind to specific IP for security in multi-tenant environments"`
	HTTPListenAddress     string            `key:"blockchain_httpListenAddress" desc:"HTTP listen address for Blockchain service" default:":8082" category:"BlockChain" usage:"Port for HTTP connections" type:"string" longdesc:"### Purpose\nSpecifies the HTTP listen address for blockchain service REST API endpoints.\n\n### How It Works\nProvides HTTP alternatives to gRPC for simple queries and health checks. The dashboard and monitoring tools use this endpoint.\n\n### Format\n- **:port** - Binds to all network interfaces\n- **ip:port** - Binds to a specific interface\n\n### Examples\n- **:8082** - Listen on all interfaces (default)\n- **127.0.0.1:8082** - Listen only on localhost\n\n### Recommendations\n- Use **:port** format for containerized deployments\n- Bind to specific IP for security in multi-tenant environments"`
	MaxRetries            int               `key:"blockchain_maxRetries" desc:"Maximum retry attempts for blockchain operations" default:"3" category:"BlockChain" usage:"Retries on transient failures" type:"int" longdesc:"### Purpose\nControls how many times blockchain database operations will retry on transient failures.\n\n### How It Works\n- Applies to transient failures like database timeouts, connection issues, and recoverable errors\n- Permanent errors (constraint violations, data corruption) fail immediately without retry\n- Each retry adds latency but improves reliability\n\n### Recommendations\n- **3** (default) - Provides reasonable reliability for most environments\n- Lower values for faster failure detection in stable environments\n- Higher values for unreliable database connections"`
	RetrySleep            int               `key:"blockchain_retrySleep" desc:"Sleep between retries in milliseconds" default:"1000" category:"BlockChain" usage:"Backoff between retry attempts" type:"int" longdesc:"### Purpose\nSets the wait time in milliseconds between blockchain operation retry attempts.\n\n### How It Works\nAfter a transient failure, the service waits this duration before attempting again, allowing temporary issues to resolve. Works with MaxRetries to determine total retry window.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter | Faster recovery | Higher database load during outages |\n| Longer | Reduced database load | Slower recovery |\n\n### Recommendations\n- **1000** (default, 1 second) - Good balance for most environments\n- Increase for databases with longer recovery times"`
	StoreURL              *url.URL          `key:"blockchain_store" desc:"Database URL for blockchain state" default:"sqlite:///blockchain" category:"BlockChain" usage:"Where chain state is persisted" type:"url" longdesc:"### Purpose\nSpecifies the database URL for blockchain state storage.\n\n### How It Works\nThe blockchain service persists critical chain data to this database, including block headers, chain tips, fork information, and FSM state.\n\n### Format\n| Database | URL Format |\n|----------|------------|\n| SQLite | sqlite:///path |\n| PostgreSQL | postgres://user:pass@host/db |\n\n### Examples\n- **sqlite:///blockchain** - Local SQLite file (default)\n- **postgres://user:pass@localhost:5432/blockchain** - PostgreSQL database\n\n### Recommendations\n- **Development**: Default sqlite:///blockchain is suitable\n- **Production**: Use PostgreSQL for reliability and concurrent access\n- Ensure backup strategy is in place for this critical data"`
	FSMStateRestore       bool              `key:"fsm_state_restore" desc:"Restore FSM state on startup" default:"false" category:"BlockChain" usage:"Resume from saved state" type:"bool" longdesc:"### Purpose\n**UNUSED** - This setting is currently not functional. The implementation that sent a Restore event via the RPC service is disabled.\n\n### How It Works\nThe FSM tracks node operational state (IDLE, RUNNING, CATCHINGBLOCKS, LEGACYSYNCING). This setting was intended to restore the previous FSM state from the database on startup, but the implementation is currently disabled.\n\n### Values\n- **false** (default) - No effect (setting is unused)\n- **true** - No effect (setting is unused)\n\n### Note\nOn startup, the blockchain service always restores the last persisted FSM state from its database store regardless of this setting."`
	FSMStateChangeDelay   time.Duration     `key:"fsm_state_change_delay" desc:"Delay between FSM state changes" default:"0" category:"BlockChain" usage:"Debounce state transitions" type:"duration" longdesc:"### Purpose\nSets the minimum delay before FSM state transitions take effect.\n\n### How It Works\nAdds a debounce delay to FSM state changes, preventing rapid transitions during startup or chain reorgs and reducing UI flicker in the dashboard.\n\n### Format\nGo duration string (e.g., 500ms, 1s, 2s).\n\n### Recommendations\n- **0** (default) - Immediate transitions for most deployments\n- Set to 500ms-1s to debounce rapid state changes if UI flicker is an issue"`
	StoreDBTimeoutMillis  int               `key:"blockchain_store_dbTimeoutMillis" desc:"Database operation timeout" default:"5000" category:"BlockChain" usage:"Maximum wait for DB operations" type:"int" longdesc:"### Purpose\nSets the timeout in milliseconds for blockchain database operations.\n\n### How It Works\nDatabase queries that exceed this timeout are cancelled and trigger retry logic if retries remain. This prevents operations from hanging indefinitely.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Higher | Tolerates slow queries | Slower failure detection |\n| Lower | Faster failure detection | May timeout valid slow queries |\n\n### Recommendations\n- **5000** (default, 5 seconds) - Suitable for most queries\n- Increase for slow databases or complex queries\n- Decrease for faster failure detection in high-performance environments"`
	InitializeNodeInState string            `key:"blockchain_initializeNodeInState" desc:"Initial FSM state for node" default:"" category:"BlockChain" usage:"Override startup state" type:"string" longdesc:"### Purpose\n**UNUSED** - This setting is defined but not referenced anywhere in the codebase.\n\n### How It Works\nThis setting was intended to force the blockchain service to initialize in a specific FSM state (IDLE, RUNNING, CATCHINGBLOCKS, LEGACYSYNCING) instead of using default initialization logic, but it is not currently implemented.\n\n### Values\n- **Empty string** (default) - No effect (setting is unused)\n\n### Note\nThe initial FSM state can be set via the -localTestStartFromState CLI argument instead."`
	PostgresPool          *PostgresSettings `key:"blockchain_postgres_pool" desc:"PostgreSQL connection pool settings" category:"BlockChain" usage:"Database connection pooling" type:"*PostgresSettings" longdesc:"### Purpose\nConfigures the connection pool for PostgreSQL blockchain store.\n\n### How It Works\nControls database connection pooling behavior including pool size, connection lifetime, and idle behavior. Proper tuning is critical for high-throughput deployments.\n\n### Recommendations\n- See PostgresSettings for individual parameter documentation\n- Tune pool size based on expected concurrent database operations\n- Monitor connection usage to optimize settings"`
	RawMinerTag           bool              `key:"blockchain_raw_miner_tag" desc:"Return raw miner tag without UTF-8 sanitization" default:"false" category:"BlockChain" usage:"Disable miner tag sanitization" type:"bool" longdesc:"### Purpose\nControls whether miner tags extracted from coinbase transactions are returned raw or sanitized.\n\n### How It Works\nBy default (false), miner tags are sanitized by removing non-printable UTF-8 characters, trimming whitespace, and truncating after the second slash. When enabled (true), the raw coinbase arbitrary text is returned without any processing, preserving binary data that may be encoded.\n\n### Values\n- **false** (default) - Sanitized miner tags (removes non-printable chars, trims, truncates)\n- **true** - Raw miner text without any processing\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Disabled | Clean, readable miner names | May lose encoded data |\n| Enabled | Preserves all coinbase data | May contain binary/non-printable chars |\n\n### Recommendations\n- Keep disabled for human-readable display\n- Enable for compatibility with other explorers (e.g., WhatsOnChain) or when full coinbase text preservation is needed"`
	UseInMemoryChainCheck bool              `key:"blockchain_use_in_memory_chain_check" desc:"Use in-memory off-chain set for CheckBlockIsInCurrentChain instead of SQL recursive CTE" default:"false" category:"BlockChain" usage:"Toggle between in-memory and SQL chain membership checks" type:"bool" longdesc:"### Purpose\nControls whether CheckBlockIsInCurrentChain uses the in-memory off-chain set (fast O(1) lookup) or the original SQL recursive CTE (slower but proven).\n\n### Values\n- **true** - Use in-memory off-chain set with background refresh\n- **false** (default) - Use original SQL recursive CTE query\n\n### Recommendations\n- **true** for production deployments after validation\n- **false** to revert to proven SQL behavior if issues arise"`
	SubscriptionTimeout   time.Duration     `key:"blockchain_subscription_timeout" desc:"Timeout for subscription readiness on client startup" default:"30s" category:"BlockChain" usage:"How long to wait for subscription to be ready" type:"duration" longdesc:"### Purpose\nControls how long the blockchain client waits for the subscription to be established and the FSM state to be fetched during startup.\n\n### How It Works\nWhen a new blockchain client connects, it subscribes to the server and waits for the subscription to be ready. If the subscription is not ready within this timeout, the client proceeds anyway with a warning.\n\n### Format\nGo duration string (e.g., 10s, 30s, 1m).\n\n### Recommendations\n- **30s** (default) - Suitable for most deployments\n- Increase for slow networks or heavily loaded blockchain services\n- Decrease for faster startup in stable environments"`

	HeartbeatInterval time.Duration `key:"blockchain_heartbeat_interval" desc:"Interval for server heartbeat broadcasts" default:"10s" category:"BlockChain" usage:"Server PING broadcast frequency and client heartbeat recency threshold" type:"duration" longdesc:"### Purpose\nControls how frequently the blockchain service broadcasts PING heartbeat notifications to all subscribers.\n\n### How It Works\nThe blockchain server periodically sends PING notifications to all connected clients (propagation, block assembly, etc.) to maintain subscription health. Clients track the timestamp of the last received heartbeat and use a threshold of **3 × this interval** when evaluating stream receive failures.\n\n### Server Behavior\n- Broadcasts PING notifications at this interval to all subscribers\n- Logged at startup with configured value\n\n### Client Behavior\n- Tracks timestamp of last received PING\n- Uses **3 × interval** as a heartbeat recency threshold when stream.Recv() returns an error\n- Sets FSM state to IDLE on receive errors if the last heartbeat is older than that threshold\n- Automatic reconnection is driven by stream receive failures, not by a separate heartbeat timer\n- The Health() endpoint checks subscription readiness (initial FSM state fetch) and gRPC connectivity\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter (5s) | Faster heartbeat cadence | Higher network overhead |\n| Longer (30s-60s) | Lower overhead | Slower stale-on-error classification |\n\n### Format\nGo duration string (e.g., 5s, 10s, 30s).\n\n### Examples\n- **10s** (default) - Server sends every 10s; clients use 30s recency threshold on errors\n- **5s** - Server sends every 5s; clients use 15s recency threshold on errors\n- **30s** - Server sends every 30s; clients use 90s recency threshold on errors\n\n### Recommendations\n- **10s** (default) - Good balance for most deployments\n- Increase to 30s-60s in stable, low-latency networks to reduce overhead\n- Decrease to 5s for more frequent heartbeats in unreliable networks\n- Single setting keeps server heartbeat cadence and client recency threshold aligned"`

	// Peer registry persistence — routes through stores/blob so operators can
	// pick any backend supported by blob.NewStore (file://, s3://, memory://,
	// etc.) instead of the registry hardcoding raw file I/O.
	PeerRegistryStore        *url.URL      `key:"blockchain_peerRegistryStore" desc:"Blob store URL for peer registry persistence" default:"" category:"BlockChain" usage:"Where the peer registry is persisted across restarts" type:"url" longdesc:"### Purpose\nSpecifies the blob store URL where the centralized peer registry envelope is persisted.\n\n### How It Works\nThe registry envelope (peers + ban scores) is serialised to JSON and written to a single key in the configured blob.Store on every save tick and on shutdown. On startup it is loaded back; stale entries are dropped per the configured TTL.\n\n### Values\n- **Empty** (default) - Persistence disabled; registry starts empty on every restart.\n- **file:///path/to/dir** - Local on-disk blob store (default for single-node deployments).\n- Any backend blob.NewStore accepts (s3://, memory://, etc.)."`
	PeerRegistrySaveInterval time.Duration `key:"blockchain_peerRegistrySaveInterval" desc:"How often the peer registry is saved to the blob store" default:"60s" category:"BlockChain" usage:"Registry save frequency" type:"duration" longdesc:"### Purpose\nControls how frequently the in-memory peer registry is persisted.\n\n### How It Works\nA background goroutine writes the registry envelope to the configured blob store at this interval. The store backend is responsible for atomic publication.\n\n### Values\n- **60s** (default) - Saves once per minute\n- Shorter values reduce data loss window on crash\n- Longer values reduce I/O overhead"`
}
