package settings

import (
	"net/url"
	"time"
)

// CoinbaseSettings configures coinbase transaction handling and mining rewards.
type CoinbaseSettings struct {
	DB                          string        `key:"coinbaseDB" desc:"Database connection string for coinbase" default:"" category:"Coinbase" usage:"Database for coinbase coordination" type:"string" longdesc:"### Purpose\nLegacy database connection string for coordinated mining setups.\n\n### How It Works\nUsed in multi-miner deployments where mining rewards are distributed according to contribution. Stores mining pool state and reward distribution history.\n\n### Recommendations\n- Configure only for mining pool deployments\n- Use coinbase_store for new deployments (preferred)"`
	UserPwd                     string        `redact:"true" key:"coinbaseDBUserPwd" desc:"Database user password for coinbase" default:"" category:"Coinbase" usage:"Authentication for coinbase database" type:"string" longdesc:"### Purpose\nPassword for coinbase database authentication.\n\n### Security\n**Keep this secure** - provides access to mining reward distribution data and coordination state.\n\n### Recommendations\n- Use environment variables or secrets management\n- Rotate credentials periodically"`
	ArbitraryText               string        `key:"coinbase_arbitrary_text" desc:"Arbitrary text to include in coinbase transactions" default:"" category:"Coinbase" usage:"Often used for miner identification" type:"string" longdesc:"### Purpose\nCustom text embedded in coinbase transactions, typically used for miner or pool identification.\n\n### How It Works\nThe text is included in the coinbase transaction's input script (scriptSig). Common uses include miner identification, version signaling, and embedding messages in blocks.\n\n### Format\nPlain text string. Limited by consensus rules to fit within the coinbase input script (approximately 100 bytes total for the entire script including block height).\n\n### Recommendations\n- Keep short to leave room for block height encoding\n- Use for pool branding or node identification"`
	GRPCAddress                 string        `key:"coinbase_grpcAddress" desc:"gRPC address for Coinbase service" default:"" category:"Coinbase" usage:"Address for coinbase distribution coordination" type:"string" longdesc:"### Purpose\nSpecifies the client connection address for the Coinbase coordination gRPC service.\n\n### Format\n**host:port** - Where host is a hostname, IP address, or DNS name.\n\n### Examples\n- **localhost:9907** - Local development\n- **coinbase.internal:9907** - Internal DNS\n- **10.0.1.50:9907** - Direct IP address\n\n### Recommendations\n- Use internal DNS or service mesh addresses in production\n- Configure only for coordinated mining pool deployments"`
	GRPCListenAddress           string        `key:"coinbase_grpcListenAddress" desc:"gRPC listen address for Coinbase service" default:"" category:"Coinbase" usage:"Port for coinbase coordination" type:"string" longdesc:"### Purpose\nSpecifies the server binding address for the Coinbase coordination gRPC service.\n\n### Format\n- **:port** - Binds to all network interfaces\n- **ip:port** - Binds to a specific interface\n\n### Examples\n- **:9907** - Listen on all interfaces\n- **127.0.0.1:9907** - Listen only on localhost\n- **10.0.1.50:9907** - Listen on specific interface\n\n### Recommendations\n- Use **:port** format for containerized deployments\n- Bind to specific IP for security in multi-tenant environments"`
	NotificationThreshold       int           `key:"coinbase_notification_threshold" desc:"Threshold for coinbase notifications" default:"0" category:"Coinbase" usage:"Notification trigger threshold" type:"int" longdesc:"### Purpose\nMinimum reward amount in satoshis that triggers Slack notifications.\n\n### How It Works\nWhen a block is mined, the coinbase reward is compared against this threshold. Notifications are only sent if the reward exceeds this value.\n\n### Values\n- **0** (default) - Disable threshold-based filtering (notify on all blocks)\n- **N > 0** - Only notify when reward exceeds N satoshis\n\n### Recommendations\n- Set higher to filter out test blocks or dust rewards\n- Useful for reducing notification noise in development environments"`
	P2PPeerID                   string        `key:"coinbase_p2p_peer_id" desc:"P2P peer ID for coinbase coordination" default:"" category:"Coinbase" usage:"Peer identifier for coinbase network" type:"string" longdesc:"### Purpose\nUnique identifier for this node in the coinbase coordination P2P network.\n\n### How It Works\nUsed to identify this miner in the reward distribution pool. If not specified, derived automatically from the P2P private key.\n\n### Recommendations\n- Leave empty to use auto-generated ID from private key\n- Set explicitly only if you need a stable, predictable peer ID"`
	P2PPrivateKey               string        `redact:"true" key:"coinbase_p2p_private_key" desc:"P2P private key for coinbase coordination" default:"" category:"Coinbase" usage:"Authentication for coinbase P2P network" type:"string" longdesc:"### Purpose\nPrivate key for secure authentication in the coinbase coordination P2P network.\n\n### How It Works\nUsed for signing coordination messages and proving identity when distributing mining rewards among pool participants.\n\n### Security\n**Keep this key secure** - compromise allows impersonation in reward distribution.\n\n### Recommendations\n- Use environment variables or secrets management\n- Generate unique keys for each mining node"`
	P2PStaticPeers              []string      `key:"coinbase_p2p_static_peers" desc:"Static P2P peers for coinbase (pipe-separated)" default:"" category:"Coinbase" usage:"Known coinbase coordination peers" type:"[]string" longdesc:"### Purpose\nList of trusted peer addresses for coinbase coordination.\n\n### How It Works\nThese peers are always connected to for reward distribution synchronization. Unlike dynamic peer discovery, static peers provide reliable coordination endpoints.\n\n### Format\nPipe-separated multiaddrs:\n**/ip4/192.168.1.100/tcp/9906/p2p/QmPeerId|/ip4/192.168.1.101/tcp/9906/p2p/QmPeerId2**\n\n### Recommendations\n- Configure all pool coordinator nodes as static peers\n- Use for mining pools with known infrastructure"`
	ShouldWait                  bool          `key:"coinbase_should_wait" desc:"Wait for coinbase coordination" default:"false" category:"Coinbase" usage:"Enable for coordinated mining" type:"bool" longdesc:"### Purpose\nControls whether block assembly waits for coinbase service coordination before finalizing blocks.\n\n### How It Works\nWhen enabled, block assembly pauses until the coinbase coordination service confirms reward distribution parameters. This ensures consistent payouts across pool participants.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| true | Coordinated pool payouts | Added latency |\n| false | No coordination delay | Solo mining only |\n\n### Recommendations\n- **true** - Mining pool setups requiring coordinated reward distribution\n- **false** (default) - Solo mining deployments"`
	Store                       *url.URL      `key:"coinbase_store" desc:"Database URL for coinbase storage" default:"" category:"Coinbase" usage:"Coinbase coordination database" type:"url" longdesc:"### Purpose\nDatabase URL for storing coinbase coordination state and reward distribution history.\n\n### Format\nDatabase connection URL with scheme:\n- **sqlite:///path/to/db** - SQLite file\n- **sqlitememory:///name** - In-memory SQLite\n- **postgres://user:pass@host:port/db** - PostgreSQL\n\n### How It Works\nUsed in mining pools to track contributions and ensure fair reward distribution across participants.\n\n### Recommendations\n- Use PostgreSQL for production mining pools\n- SQLite suitable for testing and single-node setups"`
	StoreDBTimeoutMillis        int           `key:"coinbase_store_dbTimeoutMillis" desc:"Database timeout in milliseconds for coinbase" default:"0" category:"Coinbase" usage:"Timeout for coinbase database operations" type:"int" longdesc:"### Purpose\nMaximum time to wait for coinbase database operations before timing out.\n\n### Values\n- **0** (default) - No timeout (wait indefinitely)\n- **N > 0** - Timeout after N milliseconds\n\n### Recommendations\n- Set to 0 for most deployments\n- Increase if experiencing timeout errors during high-load mining operations\n- Consider 5000-10000ms for production systems with high latency storage"`
	WaitForPeers                bool          `key:"coinbase_wait_for_peers" desc:"Wait for peers before coinbase operations" default:"false" category:"Coinbase" usage:"Ensure peer connectivity" type:"bool" longdesc:"### Purpose\nControls whether the service waits for P2P peer connections before proceeding with coinbase operations.\n\n### How It Works\nWhen enabled, ensures the coordination network is established before mining begins. Prevents scenarios where blocks are mined but reward distribution fails due to network issues.\n\n### Recommendations\n- **true** - Recommended for pool mining to prevent reward distribution issues\n- **false** (default) - Solo mining or when coordination is not required"`
	WalletPrivateKey            string        `redact:"true" key:"coinbase_wallet_private_key" desc:"Private key for coinbase rewards" default:"" category:"Coinbase" usage:"Keep secure; used to receive mining rewards" type:"string" longdesc:"### Purpose\nPrivate key (WIF format) that receives mining rewards from coinbase transactions.\n\n### How It Works\nThe public key derived from this private key is used to create the coinbase transaction output. All block rewards are sent to this address.\n\n### Security\n**Back up this key securely** - losing it means losing all mining rewards. Consider:\n- Hardware security modules (HSM) for production\n- Encrypted backups in multiple locations\n- Never commit to version control\n\n### Recommendations\n- Use BlockAssembly.MinerWalletPrivateKeys for multiple payout addresses\n- For mining pools, this may be the pool's master wallet key"`
	PeerStatusTimeout           time.Duration `key:"peerStatus_timeout" desc:"Timeout for peer status checks" default:"30s" category:"Coinbase" usage:"How long to wait for peer status" type:"duration" longdesc:"### Purpose\nMaximum time to wait when checking peer connectivity status in the coinbase coordination network.\n\n### How It Works\nIf peers don't respond within this timeout, they're considered offline for reward distribution purposes. This affects peer selection for coordination messages.\n\n### Recommendations\n- **30s** (default) - Suitable for most network conditions\n- Increase for high-latency networks\n- Decrease for faster failover to alternative peers"`
	SlackChannel                string        `key:"slack_channel" desc:"Slack channel for coinbase notifications" default:"" category:"Coinbase" usage:"Slack integration for mining alerts" type:"string" longdesc:"### Purpose\nSlack channel ID or name where mining notifications are sent.\n\n### How It Works\nWhen blocks are successfully mined, notifications are posted to this channel. Requires slack_token to be configured.\n\n### Format\n- **#channel-name** - Channel by name\n- **C01234567** - Channel by ID\n\n### Recommendations\n- Use channel ID for reliability (channel names can change)\n- Create dedicated channel for mining alerts to avoid noise"`
	SlackToken                  string        `redact:"true" key:"slack_token" desc:"Slack token for notifications" default:"" category:"Coinbase" usage:"Authentication for Slack integration" type:"string" longdesc:"### Purpose\nSlack API authentication token for sending mining notifications.\n\n### How It Works\nUsed to authenticate with Slack API when posting block mined notifications. Requires a Bot token or OAuth token with chat:write permissions.\n\n### Security\n**Keep this token secure** - provides access to post messages to your Slack workspace.\n\n### Recommendations\n- Use environment variables or secrets management\n- Create dedicated Slack app with minimal permissions\n- Rotate tokens periodically"`
	TestMode                    bool          `key:"coinbase_test_mode" desc:"Enable coinbase test mode" default:"false" category:"Coinbase" usage:"For testing without real rewards" type:"bool" longdesc:"### Purpose\nEnables test mode for coinbase service development and testing.\n\n### How It Works\nIn test mode, reward distribution is simulated without actual wallet operations. Coordination messages are processed but no real funds are transferred.\n\n### Warning\n**Never enable in production** - will result in lost mining rewards.\n\n### Recommendations\n- **true** - Development and testing environments only\n- **false** (default) - All production deployments"`
	P2PPort                     int           `key:"p2p_port_coinbase" desc:"P2P port for coinbase coordination" default:"9906" category:"Coinbase" usage:"Port for coinbase P2P communication" type:"int" longdesc:"### Purpose\nTCP port for coinbase coordination P2P network.\n\n### How It Works\nUsed for reward distribution synchronization among pool miners. Separate from the main P2P network to isolate coordination traffic.\n\n### Recommendations\n- **9906** (default) - Standard coinbase coordination port\n- Must be accessible from other pool participants if running a distributed mining pool\n- Configure firewall rules to allow traffic from trusted pool nodes only"`
	DistributorFailureTolerance int           `key:"distributor_failure_tolerance" desc:"Failure tolerance for distributor" default:"0" category:"Coinbase" usage:"Number of failures before alerting" type:"int" longdesc:"### Purpose\nNumber of consecutive reward distribution failures tolerated before triggering alerts or escalation.\n\n### How It Works\nTracks consecutive failures in reward distribution. When threshold is exceeded, alerts are triggered via configured notification channels.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| 0 | Immediate alerting | More alert noise |\n| N > 0 | Reduced noise | Delayed problem detection |\n\n### Recommendations\n- **0** (default) - Alert immediately on any failure for critical systems\n- **2-3** - Tolerate transient failures in stable environments"`
	DistributorTimeout          time.Duration `key:"distributor_timeout" desc:"Timeout for distributor operations" default:"30s" category:"Coinbase" usage:"Maximum wait for distribution" type:"duration" longdesc:"### Purpose\nMaximum time allowed for reward distribution operations to complete.\n\n### How It Works\nLimits the total time for distribution operations including database updates and P2P coordination. Operations exceeding this timeout are cancelled and may be retried.\n\n### Recommendations\n- **30s** (default) - Suitable for most deployments\n- Increase if distribution involves many participants or slow database operations\n- Decrease for faster failure detection in reliable environments"`
}
