package settings

import "time"

// P2PSettings configures the peer-to-peer networking layer.
type P2PSettings struct {
	GRPCAddress       string `key:"p2p_grpcAddress" desc:"gRPC address for P2P service" default:"" category:"P2P" usage:"Address for P2P service communication" type:"string" longdesc:"### Purpose\nClient connection address for the P2P gRPC service. Used by other internal services to communicate with the P2P service for peer management operations including GetPeers, BanPeer, RecordBytesDownloaded, GetPeerRegistry, and ReportInvalidBlock/Subtree.\n\n### Format\n**host:port** - Where host is a hostname, IP address, or DNS name.\n\n### Examples\n- **localhost:9906** - Local development\n- **p2p.internal:9906** - Internal DNS\n- **10.0.1.50:9906** - Direct IP address\n\n### Recommendations\n- Leave **empty** to auto-infer from GRPCListenAddress\n- Use internal DNS or service mesh addresses in production\n- Use localhost only for local development"`
	GRPCListenAddress string `key:"p2p_grpcListenAddress" desc:"gRPC listen address for P2P service" default:":9906" category:"P2P" usage:"Port for P2P gRPC communication" type:"string" longdesc:"### Purpose\nServer binding address for the P2P gRPC service. Accepts incoming gRPC requests from other Teranode services.\n\n### Format\n- **:port** - Binds to all network interfaces\n- **ip:port** - Binds to a specific interface\n\n### Examples\n- **:9906** - Listen on all interfaces (default)\n- **127.0.0.1:9906** - Listen only on localhost\n- **:19906, :29906** - Multi-node prefix for multiple instances on same host\n\n### Recommendations\n- Use **:port** format for containerized deployments\n- Bind to specific IP for security in multi-tenant environments"`

	HTTPAddress       string `key:"p2p_httpAddress" desc:"HTTP address for P2P service" default:"localhost:9906" category:"P2P" usage:"Full HTTP URL for P2P service" type:"string" longdesc:"### Purpose\nClient connection URL for the P2P HTTP service. Used for health checks and WebSocket connections.\n\n### How It Works\nExposes HTTP endpoints for P2P operations:\n- **/health** - Health check endpoint\n- **/p2p-ws** - WebSocket for real-time peer events including block/subtree announcements and node status heartbeats\n\n### Format\n**host:port** (e.g., localhost:9906)\n\n### Recommendations\n- Use **localhost:9906** for local development (default)\n- Use internal DNS or load balancer address in production"`
	HTTPListenAddress string `key:"p2p_httpListenAddress" desc:"HTTP listen address for P2P service" default:"" category:"P2P" usage:"Alternative HTTP interface for P2P" type:"string" longdesc:"### Purpose\nServer binding address for the P2P HTTP service. Allows binding to a different address than what is advertised externally.\n\n### How It Works\n- If **empty**, uses HTTPAddress for binding\n- Useful for binding to specific interface while advertising a different external address\n\n### Format\n- **:port** - Binds to all interfaces\n- **ip:port** - Binds to specific interface\n\n### Examples\nBind to **:9906** (all interfaces) while HTTPAddress advertises **external.example.com:9906**\n\n### Recommendations\n- Leave empty for most deployments\n- Set explicitly when behind NAT or load balancer"`

	ListenAddresses    []string `key:"p2p_listen_addresses" desc:"Multiaddr listen addresses for P2P network (pipe-separated)" default:"" category:"P2P" usage:"Example: /ip4/0.0.0.0/tcp/9905" type:"[]string" longdesc:"### Purpose\nSpecifies which network interfaces libp2p binds to for peer connections using multiaddr format. Supports multiple addresses for multi-homing.\n\n### Format\n- **/ip4/{ip}/tcp/{port}** - IPv4 address\n- **/ip6/{ip}/tcp/{port}** - IPv6 address\n- **Pipe-separated** for multiple values\n\n### Examples\n- **/ip4/0.0.0.0/tcp/9905** - All IPv4 interfaces\n- **/ip6/::/tcp/9905** - All IPv6 interfaces\n- **/ip4/0.0.0.0/tcp/9905|/ip6/::/tcp/9905** - Dual-stack\n\n### Warning\n**REQUIRED** setting - no default. Node will fail to start without this configured."`
	AdvertiseAddresses []string `key:"p2p_advertise_addresses" desc:"Multiaddr addresses to advertise (pipe-separated)" default:"" category:"P2P" usage:"Override listen addresses for external access" type:"[]string" longdesc:"### Purpose\nAddresses advertised to other peers for connecting back to this node. Overrides auto-detected addresses.\n\n### How It Works\n- When **empty** and SharePrivateAddresses=false: go-p2p auto-detects public IPs via libp2p Identify protocol\n- When **empty** and SharePrivateAddresses=true: uses ListenAddresses\n- When **set**: explicitly advertises these addresses to peers\n\n### Format\n**/ip4/{public_ip}/tcp/{port}** - Pipe-separated for multiple values\n\n### Examples\n- **/ip4/203.0.113.5/tcp/9905** - Single public IP\n- Behind NAT: listen on **/ip4/0.0.0.0/tcp/9905**, advertise **/ip4/203.0.113.5/tcp/9905**\n\n### Recommendations\n- Leave empty for auto-detection in most deployments\n- Set explicitly when behind NAT/firewall with port forwarding\n- Set when listening on private IPs but accessible via public IP"`
	ListenMode         string   `key:"listen_mode" desc:"P2P listen mode: 'full', 'listen_only', or 'silent'" default:"full" category:"P2P" usage:"Use 'listen_only' for passive nodes, 'silent' for outbound-only stealth nodes" type:"string" longdesc:"### Purpose\nControls P2P network participation mode - whether the node actively participates, passively observes, or connects silently without advertising.\n\n### Options\n- **full** (default) - Receives AND propagates blocks/subtrees/rejected transactions, advertises DataHub URL for sync, participates as full network peer\n- **listen_only** - Receives data but does not propagate, no DataHub URL advertisement, cannot be selected as sync source\n- **silent** - Connects outbound to configured peers and syncs data, but does not advertise itself (no DHT advertisement, no address announcement, no node_status publishing). Minimises attack surface for monitoring or security-sensitive deployments.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| full | Full network participation | Higher bandwidth, serves data to others |\n| listen_only | Lower resource usage, reduced visibility | Cannot contribute to network, no sync serving |\n| silent | Maximum stealth, minimal inbound exposure | Cannot be discovered by or serve other peers |\n\n### Recommendations\n- **full** - Production mining/validation nodes\n- **listen_only** - Monitoring nodes, analytics nodes, nodes behind restrictive firewalls\n- **silent** - Security-conscious deployments, development observers, nodes that must minimise inbound connections"`

	PeerID string `key:"p2p_peer_id" desc:"Peer ID for this node" default:"" category:"P2P" usage:"Derived from private key if not specified" type:"string" longdesc:"### Purpose\nOverride for peer identity (libp2p peer ID). Normally derived automatically from the PrivateKey.\n\n### How It Works\n- Peer ID is the **base58-encoded hash** of the public key\n- Used to uniquely identify this node in the P2P network\n- Other peers use this ID for routing and connection management\n\n### Recommendations\n- Leave **empty** for automatic derivation (recommended)\n- Only set for advanced configurations or testing scenarios"`
	Port   int    `key:"p2p_port" desc:"P2P port number" default:"9906" category:"P2P" usage:"Port for P2P connections" type:"int" longdesc:"### Purpose\nTCP port for libp2p peer-to-peer connections.\n\n### How It Works\nUsed when AdvertiseAddresses is configured to append port to advertise addresses.\n\n### Values\n- **9906** (default) - Standard P2P port for single-node deployments\n- **19906, 29906, 39906** - Multi-node prefixes for multiple instances on same host\n\n### Warning\nMust match the port in ListenAddresses and AdvertiseAddresses for proper peer discovery."`

	PrivateKey string `key:"p2p_private_key" desc:"Private key for P2P identity" default:"" category:"P2P" usage:"Used for peer authentication and signing" type:"string" longdesc:"### Purpose\nEd25519 private key for libp2p node identity and message signing.\n\n### How It Works\nThe key is loaded in priority order:\n1. This setting value\n2. **{PeerCacheDir}/p2p.key** file (auto-created if missing)\n3. Auto-generate and save to file\n\n### Format\n64-byte hex string (32 bytes private + 32 bytes public key)\n\n### Security\n- Peer ID is cryptographically derived from this key\n- Keep secure with file permissions **0600**\n- **Changing key changes peer identity**, causing network to see node as a different peer\n- Loss of key means loss of accumulated reputation with other peers"`

	BlockTopic      string `key:"p2p_block_topic" desc:"P2P topic for block messages" default:"" category:"P2P" usage:"Pubsub topic for block propagation" type:"string" longdesc:"### Purpose\nPubsub topic name for block announcements across the P2P network.\n\n### How It Works\nWhen Block Assembly creates a new block, P2P Server publishes a **BlockMessage** containing hash, height, DataHub URL, Peer ID, header, and client name. Other nodes subscribe to discover new blocks, update peer heights, and trigger sync/validation.\n\n### Format\n**{TopicPrefix}-{BlockTopic}** (e.g., mainnet-block)\n\n### Warning\n- **REQUIRED** setting - node will not function without this configured\n- **Disabled** in listen_only mode (does not publish, only subscribes)"`
	NodeStatusTopic string `key:"p2p_node_status_topic" desc:"P2P topic for node status messages" default:"" category:"P2P" usage:"Pubsub topic for node status updates" type:"string" longdesc:"### Purpose\nPubsub topic for periodic node heartbeats, enabling peer discovery and network health monitoring.\n\n### How It Works\nBroadcasts status every **10 seconds** containing: best block height/hash, FSM state, transaction/subtree counts, storage mode (full/pruned), sync peer info, uptime, client version, mining fees, and connected peers count.\n\n### Format\n**{TopicPrefix}-{NodeStatusTopic}** (e.g., mainnet-node_status)\n\n### Security\nMessages validate sender **PeerID** matches message PeerID to prevent spoofing attacks.\n\n### Recommendations\n- **REQUIRED** setting for network participation\n- Used for peer height discovery, network monitoring, sync peer selection, and reputation tracking"`
	RejectedTxTopic string `key:"p2p_rejected_tx_topic" desc:"P2P topic for rejected transactions" default:"" category:"P2P" usage:"Pubsub topic for rejected transaction notifications" type:"string" longdesc:"### Purpose\nPubsub topic for broadcasting invalid transaction notifications to prevent propagation across the network.\n\n### How It Works\n1. Validator rejects transaction\n2. Kafka message sent internally\n3. P2P Server receives and broadcasts to network\n4. Only broadcasts internal rejections (does not re-broadcast external rejections)\n\nMessage contains TX hash, rejection reason (double_spend, invalid_signature, etc.), and Peer ID.\n\n### Format\n**{TopicPrefix}-{RejectedTxTopic}** (e.g., mainnet-rejected_tx)\n\n### Warning\n- **REQUIRED** setting for full network participation\n- **Disabled** in listen_only mode (does not broadcast rejections)"`
	SubtreeTopic    string `key:"p2p_subtree_topic" desc:"P2P topic for subtree messages" default:"" category:"P2P" usage:"Pubsub topic for subtree propagation" type:"string" longdesc:"### Purpose\nPubsub topic for Merkle subtree announcements, enabling efficient large block propagation.\n\n### How It Works\n1. Subtree Validation validates the subtree\n2. Blockchain stores the validated subtree\n3. P2P Server publishes **SubtreeMessage** (hash, DataHub URL, peer ID, client name)\n4. Other nodes receive and trigger subtree download/validation\n\nThis enables efficient large block propagation using the **Merkle tree structure** for parallel validation.\n\n### Format\n**{TopicPrefix}-{SubtreeTopic}** (e.g., mainnet-subtree)\n\n### Warning\n- **REQUIRED** setting for block validation participation\n- **Disabled** in listen_only mode (does not publish, only subscribes)"`

	StaticPeers    []string `key:"p2p_static_peers" desc:"Static peer addresses to always connect to (pipe-separated)" default:"" category:"P2P" usage:"Use for known reliable peers" type:"[]string" longdesc:"### Purpose\nHardcoded peer connections maintained persistently by libp2p. Unlike bootstrap peers, these connections are kept active permanently.\n\n### How It Works\nlibp2p maintains persistent connections to these peers, reconnecting automatically if disconnected.\n\n### Format\nMultiaddr strings with peer ID (pipe-separated for multiple):\n- **/ip4/{ip}/tcp/{port}/p2p/{peerID}**\n- **/dns/{domain}/tcp/{port}/p2p/{peerID}**\n\n### Examples\n**/ip4/203.0.113.5/tcp/9905/p2p/QmPeer1ID|/dns/peer2.example.com/tcp/9905/p2p/QmPeer2ID**\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Static Peers | Guaranteed connectivity, works without DHT | Manual maintenance, single points of failure |\n| Bootstrap Peers | DHT-based discovery | Just initial entry points, not permanent |\n\n### Recommendations\n- Use for known reliable peers in production\n- Use for private networks without DHT\n- Use to guarantee connectivity to specific trusted nodes"`
	BootstrapPeers []string `key:"p2p_bootstrap_peers" desc:"Bootstrap peer addresses for DHT discovery (pipe-separated)" default:"" category:"P2P" usage:"Initial peers for network discovery" type:"[]string" longdesc:"### Purpose\nInitial entry points for joining the DHT (Distributed Hash Table) network. First peers contacted on startup to discover other peers.\n\n### How It Works\nBootstrap peers serve as DHT entry points - they help the node discover other peers but are not permanently connected like static peers.\n\n### Format\nMultiaddr strings (pipe-separated for multiple):\n- **/dnsaddr/{bootstrap.domain}**\n- **/ip4/{ip}/tcp/{port}/p2p/{peerID}**\n\n### Examples\n**/dnsaddr/bootstrap.bitcoinsv.io|/ip4/203.0.113.10/tcp/9905/p2p/QmBootstrapID**\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Bootstrap Peers | Dynamic peer discovery via DHT | Requires DHT participation |\n| Static Peers | No DHT needed | Manual peer list management |\n\n### Recommendations\n- Use for joining public networks (mainnet/testnet)\n- Leave empty for private networks using only StaticPeers"`

	// Peer persistence (from go-p2p improvements)
	PeerCacheDir string `key:"p2p_peer_cache_dir" desc:"Directory for peer cache file" default:"" category:"P2P" usage:"Empty = binary directory" type:"string" longdesc:"### Purpose\nDirectory for persisting discovered peers to disk, enabling faster network rejoins on restart.\n\n### How It Works\nFiles created in this directory:\n- **teranode_peers.json** - Discovered peer multiaddrs from DHT (managed by go-p2p library)\n- **p2p.key** - Ed25519 private key (if not in PrivateKey setting)\n\n### Values\n- **empty** (default) - Uses binary directory\n- **/path/to/cache** - Custom cache directory\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Persistent cache | Faster startup, preserves reputation | Disk space, stale peers possible |\n| No cache | Fresh peer discovery | Slower startup, higher bootstrap load |"`

	BanThreshold int           `key:"p2p_ban_threshold" desc:"Misbehavior score threshold before banning a peer" default:"100" category:"P2P" usage:"Lower values are more strict" type:"int" longdesc:"### Purpose\nMisbehavior score threshold that triggers a temporary peer ban when reached.\n\n### How It Works\nPenalty points accumulate per violation:\n- **Invalid Subtree**: +10 points\n- **Invalid Block**: +10 points\n- **Protocol Violation**: +20 points\n- **Catchup Failure**: +30 points\n- **Spam**: +50 points\n\nScore decays at **-1 point/minute**. When score >= threshold, peer is banned for BanDuration. After ban expires, score resets.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Lower (50) | Strict enforcement, faster bad peer isolation | May ban peers with transient issues |\n| Higher (200) | Tolerates transient issues | Slower to isolate bad actors |\n\n### Recommendations\n- **100** (default) - Production environments\n- **200** - Testing/development with unstable peers"`
	BanDuration  time.Duration `key:"p2p_ban_duration" desc:"Duration to ban misbehaving peers" default:"24h" category:"P2P" usage:"Longer durations prevent repeated abuse" type:"duration" longdesc:"### Purpose\nControls how long peers remain banned after exceeding BanThreshold.\n\n### How It Works\nAfter ban expires, the ban score resets and the peer can reconnect. Ban status syncs with PeerRegistry.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter (1h) | Quick recovery from transient issues | Bad actors can return sooner |\n| Longer (7d) | Persistent protection from bad actors | May permanently lose legitimate peers |\n\n### Recommendations\n- **1h** - Testing/development (quick recovery from mistakes)\n- **24h** (default) - Production (standard protection)\n- **7d** - Strict enforcement for persistent bad actors"`

	// Sync manager configuration
	ForceSyncPeer string `key:"p2p_force_sync_peer" desc:"Force sync from specific peer ID" default:"" category:"P2P" usage:"Overrides automatic peer selection" type:"string" longdesc:"### Purpose\nOverride automatic peer selection for blockchain sync, forcing sync from a specific peer regardless of eligibility.\n\n### How It Works\nWhen set, ignores all eligibility checks (reputation, ban status, height) and syncs exclusively from this peer.\n\nWhen **empty** (default), SyncCoordinator uses reputation-based selection:\n- **Phase 1**: Selects full nodes by reputation/response-time/ban-score/height\n- **Phase 2**: Falls back to youngest pruned nodes if AllowPrunedNodeFallback=true\n\n### Format\nlibp2p peer ID string (e.g., **QmPeerID...**)\n\n### Warning\nBypasses all safety checks. Only use for debugging, testing, or forcing sync from a known trusted peer."`

	// Address sharing configuration
	// SharePrivateAddresses controls whether to advertise private/local IP addresses to peers.
	// When true (default), allows local/test environments to work properly.
	// When false, only public addresses are advertised (better for production privacy).
	SharePrivateAddresses bool `key:"p2p_share_private_addresses" desc:"Advertise private/local IP addresses to peers" default:"true" category:"P2P" usage:"Enable for local/test environments" type:"bool" longdesc:"### Purpose\nControls whether to advertise RFC1918 private IP addresses (10.x, 172.16.x, 192.168.x) to peers.\n\n### How It Works\n- **true** (default): Advertises ListenAddresses even if private, enables local/test environment connectivity\n- **false**: Only advertises public IPs, go-p2p auto-detects public addresses via libp2p Identify protocol\n\nIf AdvertiseAddresses is explicitly set, this setting is **ignored**.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| true | Local network connectivity works | Exposes internal network topology |\n| false | Privacy, no internal IP exposure | Local dev environments may not work |\n\n### Recommendations\n- **Production/Cloud**: false for privacy\n- **Local dev**: true\n- Works with AllowPrivateIPs (both must be true for full local network connectivity)"`
	// Peer map cleanup configuration
	PeerMapMaxSize         int           `key:"p2p_peer_map_max_size" desc:"Maximum entries in peer maps" default:"100000" category:"P2P" usage:"Prevents memory exhaustion" type:"int" longdesc:"### Purpose\nLimits entries in peer tracking maps (blockPeerMap, subtreePeerMap) to prevent memory exhaustion from DoS attacks.\n\n### How It Works\nMaps track which peer sent each block/subtree for ban attribution when invalid data is reported. When limit is reached, oldest entries are evicted.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Higher | Better attribution for more blocks | More memory usage |\n| Lower | Lower memory | May lose attribution for older blocks |\n\n### Recommendations\n- **100000** (default) - Handles large networks\n- Lower for memory-constrained environments\n- Higher for very large networks with many peers"`
	PeerMapTTL             time.Duration `key:"p2p_peer_map_ttl" desc:"Time-to-live for peer map entries" default:"30m" category:"P2P" usage:"How long to keep inactive peers" type:"duration" longdesc:"### Purpose\nTime-to-live for peer map entries before considered stale and eligible for cleanup.\n\n### How It Works\nEntries older than TTL are removed during periodic cleanup (every PeerMapCleanupInterval). This ensures ban attribution is available for blocks still being validated.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter (15m) | Lower memory usage | May lose attribution for slow-validating blocks |\n| Longer (1h) | Better attribution coverage | Higher memory usage |\n\n### Recommendations\n- **30m** (default) - Handles typical block validation times\n- **1h** - Large blocks with slow validation\n- **15m** - Fast-validating small blocks"`
	PeerMapCleanupInterval time.Duration `key:"p2p_peer_map_cleanup_interval" desc:"Cleanup interval for peer maps" default:"5m" category:"P2P" usage:"How often to clean up stale peers" type:"duration" longdesc:"### Purpose\nControls how often stale peer map entries are cleaned up to reclaim memory.\n\n### How It Works\nPeriodically scans blockPeerMap and subtreePeerMap, removing entries older than PeerMapTTL.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Frequent (1m) | Low memory usage | Higher CPU overhead |\n| Infrequent (15m) | Lower CPU overhead | Higher memory usage |\n\n### Recommendations\n- **5m** (default) - Balances memory efficiency and CPU overhead\n- **2m** - Memory-constrained environments\n- **10m** - High-throughput systems to reduce cleanup overhead"`

	// Peer registry cleanup configuration
	PeerRegistryMaxSize         int           `key:"p2p_peer_registry_max_size" desc:"Maximum entries in the peer registry" default:"10000" category:"P2P" usage:"Prevents unbounded growth from peer churn" type:"int" longdesc:"### Purpose\nUpper bound on the per-peer record map (services/p2p PeerRegistry). Without a bound, the registry grows for every previously-seen peer ID and slows every O(n) lookup (catchup selection, reputation queries).\n\n### How It Works\nEvery PeerRegistryCleanupInterval the registry runs TTL eviction (PeerRegistryTTL) followed by LRU enforcement of this size limit. Connected and banned peers are exempt from both phases.\n\n### Recommendations\n- **10000** (default) - generous headroom for production meshes\n- Lower in memory-constrained environments\n- Set to 0 to disable LRU enforcement (TTL only)"`
	PeerRegistryTTL             time.Duration `key:"p2p_peer_registry_ttl" desc:"Time-to-live for peer registry entries" default:"24h" category:"P2P" usage:"How long an idle peer is retained" type:"duration" longdesc:"### Purpose\nIdle entries older than this are dropped from the peer registry on each cleanup tick. Connected and banned peers are kept regardless.\n\n### Recommendations\n- **24h** (default) - keeps reputation across normal restarts\n- Shorter for high-churn networks\n- Longer to retain reputation longer at the cost of memory"`
	PeerRegistryCleanupInterval time.Duration `key:"p2p_peer_registry_cleanup_interval" desc:"Cleanup interval for peer registry" default:"1h" category:"P2P" usage:"How often to evict stale registry entries" type:"duration" longdesc:"### Purpose\nControls how often the peer registry cleanup tick runs. Each tick performs TTL eviction followed by LRU enforcement against PeerRegistryMaxSize."`

	// DHT configuration
	DHTMode            string        `key:"p2p_dht_mode" desc:"DHT mode: 'server' (advertise) or 'client' (query-only)" default:"server" category:"P2P" usage:"Use 'client' to reduce network visibility" type:"string" longdesc:"### Purpose\nControls DHT (Distributed Hash Table) participation mode for peer discovery.\n\n### Options\n- **server** (default) - Advertises node on DHT, stores provider records for other peers, helps network with peer discovery, requires periodic cleanup (DHTCleanupInterval)\n- **client** - Queries DHT for peer discovery but does not advertise or store records, reduces network visibility, lower memory footprint, relies on server-mode peers\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| server | Helps network health, full discovery | Higher memory, more network visibility |\n| client | Privacy, lower resources | Relies on server-mode peers |\n\n### Recommendations\n- **server** - Public nodes that should help network health\n- **client** - Privacy-focused nodes, nodes using only StaticPeers, Alert service"`
	DHTCleanupInterval time.Duration `key:"p2p_dht_cleanup_interval" desc:"Interval for DHT provider record cleanup" default:"24h" category:"P2P" usage:"Only applies to server mode" type:"duration" longdesc:"### Purpose\nControls how often DHT provider records are cleaned up to remove stale peer mappings.\n\n### How It Works\nDHT server nodes store provider records (mappings of content IDs to peer addresses). Over time, stale records accumulate from disconnected peers. Cleanup removes expired records, preventing memory bloat.\n\nOnly applies when DHTMode=**server**. Ignored when DHTMode=client (no provider records stored).\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Frequent (12h) | Cleaner DHT, lower memory | More CPU overhead |\n| Infrequent (48h) | Lower CPU overhead | More stale records |\n\n### Recommendations\n- **24h** (default) - Suitable for most deployments\n- **12h** - High-churn networks with frequent peer joins/leaves\n- **48h** - Stable networks with long-lived peers"`

	// EnableNAT enables UPnP/NAT-PMP automatic port mapping features.
	// When enabled, scans the local gateway (e.g., 10.0.0.1) to configure port forwarding.
	// IMPORTANT: Triggers network scanning alerts on shared hosting (Hetzner, AWS).
	// Only enable for local development behind a home router/NAT.
	// Default: false (NAT features disabled for production safety)
	EnableNAT bool `key:"p2p_enable_nat" desc:"Enable UPnP/NAT-PMP automatic port mapping" default:"false" category:"P2P" usage:"May trigger security alerts on shared hosting" type:"bool" longdesc:"### Purpose\nEnables automatic port forwarding via UPnP/NAT-PMP protocols for nodes behind NAT.\n\n### How It Works\n- Scans local gateway (e.g., 10.0.0.1) using SSDP protocol to discover router\n- Configures port forwarding for P2P port automatically\n- Enables incoming connections from internet without manual router configuration\n\n### Security\n**CRITICAL RISK** on shared hosting (Hetzner/AWS/DigitalOcean):\n- Gateway scan appears as network reconnaissance\n- Triggers intrusion detection and abuse reports\n- May result in **account suspension**\n\n### Recommendations\n- **Home networks**: Safe to use with personal router behind NAT\n- **Cloud/VPS**: **ALWAYS false** - use manual port forwarding or AdvertiseAddresses instead\n\nDefault **false** for production safety."`

	// EnableMDNS enables multicast DNS peer discovery on the local network.
	// IMPORTANT: Only enable on isolated local networks. On shared hosting (e.g., Hetzner, AWS)
	// without VLANs, mDNS broadcasts appear as network scanning and may result in abuse reports.
	// Default: false (mDNS disabled for production safety)
	// Set to true only for local development networks with proper isolation
	EnableMDNS bool `key:"p2p_enable_mdns" desc:"Enable multicast DNS peer discovery" default:"false" category:"P2P" usage:"Only for isolated local networks" type:"bool" longdesc:"### Purpose\nEnables automatic peer discovery on local network via multicast DNS (mDNS).\n\n### How It Works\n- Broadcasts to 224.0.0.251 on local subnet to discover peers\n- Useful for local development without DHT/bootstrap peers\n- Automatically finds other Teranode instances on the same network segment\n\n### Security\n**CRITICAL RISK** on shared hosting without VLAN isolation:\n- mDNS broadcasts reach other customers VMs on same subnet\n- Appears as network scanning/reconnaissance\n- Triggers intrusion detection systems\n- Results in **abuse reports and potential account suspension**\n\n### Recommendations\n- **Cloud/shared hosting**: **ALWAYS false**\n- **Isolated local networks** (VLAN segmentation): Safe to enable\n- **Home networks**: Safe to enable\n- **Private dev environments**: Safe to enable\n\nDefault **false** for production safety."`

	// AllowPrivateIPs allows connections to private/local IP addresses during peer discovery.
	// When true, allows connections to RFC1918 private networks (10.x, 172.16.x, 192.168.x).
	// IMPORTANT: Only enable on private networks. On shared hosting, this may trigger network scanning alerts.
	// Default: false (private IPs filtered for production safety)
	// Set to true only for local development or private network deployments
	AllowPrivateIPs bool `key:"p2p_allow_private_ips" desc:"Allow connections to private IP addresses" default:"false" category:"P2P" usage:"Enable for local development/testing" type:"bool" longdesc:"### Purpose\nAllows TCP connections to RFC1918 private IP addresses (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16) during peer discovery.\n\n### How It Works\n- **false** (default): Filters out private IPs from peer lists, prevents connection attempts to private networks\n- **true**: Allows connection attempts to private IPs\n\nBoth AllowPrivateIPs and SharePrivateAddresses must be **true** for full local network connectivity.\n\n### Security\n**RISK** on shared hosting:\n- Connection attempts to other customers private IPs appear as network scanning\n- Triggers intrusion detection systems\n- Results in **abuse reports**\n\n### Recommendations\n- **Isolated private networks/local dev**: true\n- **Cloud/shared hosting**: **ALWAYS false**\n\nDefault **false** for production safety."`

	// Node mode configuration (full vs pruned)
	AllowPrunedNodeFallback bool `key:"p2p_allow_pruned_node_fallback" desc:"Fall back to pruned nodes when no full nodes available" default:"true" category:"P2P" usage:"Selects youngest pruned node to minimize risk" type:"bool" longdesc:"### Purpose\nControls sync peer selection behavior when no full nodes are available.\n\n### How It Works\nNodes advertise storage mode (full or pruned) in NodeStatusTopic.\n- **true** (default): SyncCoordinator Phase 1 tries full nodes, Phase 2 falls back to youngest (lowest height) pruned node to minimize UTXO pruning risk\n- **false**: Only syncs from full nodes, waits indefinitely if none available\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| true | Sync continues even without full nodes | Risk of missing old UTXO data |\n| false | Guaranteed full history | May stall if no full nodes available |\n\n### Recommendations\n- **true** (default) - Flexibility in peer selection, allows sync when full nodes are scarce\n- **false** - Compliance/archival requirements needing guaranteed full history"`

	// This is the time we trigger a periodic evaluation in the sync coordinator
	SyncCoordinatorPeriodicEvaluationInterval time.Duration `key:"p2p_sync_coordinator_periodic_evaluation_interval" desc:"Periodic evaluation interval for sync coordinator" default:"30s" category:"P2P" usage:"How often to evaluate sync status" type:"duration" longdesc:"### Purpose\nControls how often SyncCoordinator evaluates current sync peer performance and health.\n\n### How It Works\nHealth checks performed each interval:\n- Peer still connected\n- Reputation above threshold (20)\n- Activity check (no messages for 1min = failure)\n- Caught up to peer (switch to better peer if available)\n\nIf all eligible peers attempted: enters exponential backoff (2s, 4s, 8s...up to 64s), then clears sync attempt timestamps to allow retry.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter (10s) | Quicker detection of peer issues | Higher CPU overhead |\n| Longer (60s) | Lower overhead | Slower response to peer problems |\n\n### Recommendations\n- **30s** (default) - Balances responsiveness and overhead\n- **10s** - Fast networks or testing requiring quick peer switching\n- **60s** - Stable networks to reduce evaluation overhead"`

	// On-demand HTTP health checking for peer availability
	HealthCheckEnabled bool `key:"p2p_health_check_enabled" desc:"Enable HTTP availability checking during peer selection" default:"true" category:"P2P" usage:"Uses 2s timeout for health checks" type:"bool" longdesc:"### Purpose\nEnables HTTP health checking to validate peer availability before selecting for sync.\n\n### How It Works\n- Performs HTTP GET to /health endpoint with 2-second timeout\n- Tests peer accessibility before selection\n- Reduces wasted time on unresponsive peers\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| true | More reliable peer selection | Additional HTTP overhead |\n| false | No health check overhead | May select unavailable peers |\n\n### Recommendations\n- **true** (default) - Recommended for production to ensure peer reliability"`
}
