package settings

import (
	"net/url"
	"time"
)

// RPCSettings configures the Bitcoin JSON-RPC service.
type RPCSettings struct {
	RPCUser           string        `key:"rpc_user" desc:"Username for RPC authentication" default:"" category:"RPC" usage:"Required for RPC access" type:"string" longdesc:"### Purpose\nUsername for HTTP Basic Authentication to the Bitcoin JSON-RPC API.\n\n### How It Works\nCombined with rpc_pass to form admin-level credentials that grant full access to all RPC methods including state-changing operations:\n- invalidateblock\n- setban\n- generate\n- stop\n\nCredentials are hashed using SHA256 and compared using constant-time comparison to prevent timing attacks. Format: Basic base64(rpc_user:rpc_pass) in the Authorization header.\n\n### Security\n- Also used by the dashboard for authentication (shared credentials)\n- Leave empty to disable authentication (not recommended for production)\n- See rpc_limit_user/rpc_limit_pass for read-only access"`
	RPCPass           string        `redact:"true" key:"rpc_pass" desc:"Password for RPC authentication" default:"" category:"RPC" usage:"Use a strong, unique password" type:"string" longdesc:"### Purpose\nPassword for HTTP Basic Authentication to the Bitcoin JSON-RPC API.\n\n### How It Works\nCombined with rpc_user to form admin-level credentials. The credential is hashed using SHA256 (Basic base64(user:pass)) and stored in memory for constant-time comparison.\n\n### Security\n- Use a strong, randomly generated password (32+ characters)\n- Never commit to source control\n- Rotate regularly\n- Use different passwords per environment\n- Also used for dashboard authentication\n- Leave empty to disable authentication (development only)\n- The password is never logged or exposed in API responses"`
	RPCLimitUser      string        `key:"rpc_limit_user" desc:"Username for limited RPC access" default:"" category:"RPC" usage:"For read-only RPC operations" type:"string" longdesc:"### Purpose\nUsername for limited-access HTTP Basic Authentication to the Bitcoin JSON-RPC API.\n\n### How It Works\nCombined with rpc_limit_pass to form restricted credentials that only allow read-only RPC methods:\n- getblock\n- getblockheader\n- getrawtransaction\n- getinfo\n\nLimited users are blocked from state-changing operations (invalidateblock, setban, generate, stop) with a JSON-RPC error. Credentials are hashed using SHA256 and compared using constant-time comparison. Server checks limited credentials first (before admin) for performance.\n\n### Recommendations\n- Use for API access to untrusted clients\n- Use for monitoring tools\n- Use for public endpoints without risking node configuration changes"`
	RPCLimitPass      string        `redact:"true" key:"rpc_limit_pass" desc:"Password for limited RPC access" default:"" category:"RPC" usage:"For read-only RPC operations" type:"string" longdesc:"### Purpose\nPassword for limited-access HTTP Basic Authentication to the Bitcoin JSON-RPC API.\n\n### How It Works\nCombined with rpc_limit_user to form restricted read-only credentials. The credential is hashed using SHA256 and compared using constant-time comparison. Limited-access users can call read-only methods but are blocked from state-changing operations.\n\n### Security\n- Should be different from rpc_pass to maintain separation of privileges\n- Can be less complex than admin password since it only grants read access\n- Still use reasonable strength (16+ characters) to prevent unauthorized queries\n\n### Recommendations\n- Use for public APIs\n- Use for monitoring tools\n- Use for untrusted integrations"`
	RPCMaxClients     int           `key:"rpc_max_clients" desc:"Maximum concurrent RPC clients" default:"1" category:"RPC" usage:"Increase for high-traffic environments" type:"int" longdesc:"### Purpose\nMaximum number of concurrent HTTP JSON-RPC client connections allowed.\n\n### How It Works\nWhen limit is reached, new connections are rejected with HTTP 503 Service Unavailable. Connection count is tracked atomically and separate from WebSocket connections. This prevents resource exhaustion from too many simultaneous clients.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Higher | Handles more concurrent clients | Higher memory and resource usage |\n| Lower | Lower resource usage | May reject legitimate requests |\n\n### Warning\nDefault 1 is very restrictive. Production deployments typically need 10-100+ depending on expected traffic.\n\n### Recommendations\n- Increase for high-traffic public RPC endpoints\n- Increase when using multiple monitoring tools\n- Increase for frequent programmatic access\n- Does not limit request rate per client, only total concurrent connections"`
	RPCQuirks         bool          `key:"rpc_quirks" desc:"Enable RPC quirks mode" default:"true" category:"RPC" usage:"Compatibility mode for certain clients" type:"bool" longdesc:"### Purpose\nEnables Bitcoin Core compatibility mode for handling non-standard JSON-RPC requests.\n\n### How It Works\nPer JSON-RPC 2.0 spec, requests with id:null are treated as notifications that receive no response. Bitcoin Core responds to such requests, but strict servers do not.\n\n### Values\n- **true** (default) - Responds to requests with id:null and requests without jsonrpc version field\n- **false** - Strict JSON-RPC 2.0 compliance; ignores notification-like requests\n\n### Recommendations\n- Keep enabled (true) for compatibility with existing Bitcoin tools and libraries\n- Set to false only for strict spec compliance or debugging RPC client behavior"`
	RPCListenerURL    *url.URL      `key:"rpc_listener_url" desc:"URL for RPC server to listen on" default:"" category:"RPC" usage:"Example: http://localhost:9292" type:"url" longdesc:"### Purpose\nThe HTTP URL where the Bitcoin JSON-RPC server listens for incoming connections.\n\n### Format\nscheme://host:port (e.g., http://localhost:9292 or http://0.0.0.0:9292)\n\n### How It Works\nThe RPC server binds to this address and accepts JSON-RPC requests for blockchain queries (getblock, getblockheader), transaction operations (getrawtransaction, sendrawtransaction), mining (getminingcandidate, generate), and network management (getpeerinfo, setban).\n\n### Values\n- **localhost** - Local-only access\n- **0.0.0.0** - All interfaces (requires firewall configuration)\n- **Specific IP** - Interface-specific binding\n\n### Warning\nMust be configured for RPC service to start. TLS is not currently supported at RPC layer - use a reverse proxy for HTTPS.\n\n### Recommendations\n- Standard Bitcoin RPC port is 8332, BSV commonly uses 9292\n- Use localhost for development, specific IPs or 0.0.0.0 with firewall rules for production"`
	RPCMaxRequestSize int           `key:"rpc_maxRequestSize" desc:"Maximum RPC request body size in bytes" default:"10485760" category:"RPC" usage:"Prevent memory exhaustion from oversized requests" type:"int" longdesc:"### Purpose\nLimits the maximum request body size accepted by the RPC server.\n\n### How It Works\nRequest bodies exceeding this limit are rejected with an HTTP 400 error before reading the full body into memory. Uses http.MaxBytesReader for efficient enforcement.\n\n### Values\n- **10485760** (default) - 10MB, extremely generous for JSON-RPC requests\n\n### Recommendations\n- **10MB** is far larger than any legitimate JSON-RPC request\n- Decrease for stricter protection if RPC is publicly exposed\n- JSON-RPC requests are typically under 1KB"`
	CacheEnabled      bool          `key:"rpc_cache_enabled" desc:"Enable response caching for RPC calls" default:"true" category:"RPC" usage:"Improves performance for repeated queries" type:"bool" longdesc:"### Purpose\nEnables in-memory caching of RPC responses to improve performance for repeated queries.\n\n### How It Works\nCache stores responses with a 10-second TTL and cleanup runs every minute. Cached methods include getbestblockhash, getpeerinfo, getblockchaininfo, getinfo, and getchaintips. Cache hits avoid expensive blockchain service calls, blob store retrievals, and UTXO lookups.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Enabled | Reduced backend load, faster responses | May serve slightly stale data |\n| Disabled | Always real-time data | Higher backend load |\n\n### Recommendations\n- Keep enabled (true) for production to reduce load on backend services\n- Disable when guaranteed real-time data is required\n- Disable when experiencing memory pressure\n- Disable when debugging stale response issues"`
	RPCTimeout        time.Duration `key:"rpc_timeout" desc:"Timeout for RPC requests" default:"30s" category:"RPC" usage:"Increase for slow operations" type:"duration" longdesc:"### Purpose\nMaximum time allowed for an individual RPC command to execute before being terminated.\n\n### How It Works\nEach RPC handler runs with timeout enforced via context.WithTimeout. If exceeded, client receives JSON-RPC error code -32603 (timeout). This prevents slow operations from holding connections open indefinitely. Timeout applies per RPC call, not per connection.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Longer | Allows complex operations to complete | Connections held longer |\n| Shorter | Faster failure detection | May timeout legitimate slow operations |\n\n### Recommendations\n- **30s** (default) - Suitable for most operations\n- Increase for complex blockchain queries (large block retrievals)\n- Increase for slow backend services (S3 latency)\n- Increase for mining operations (generate)\n- Decrease for strict responsiveness requirements\n- Distinct from rpc_client_call_timeout which applies to outbound client calls"`
	ClientCallTimeout time.Duration `key:"rpc_client_call_timeout" desc:"Timeout for RPC client calls" default:"5s" category:"RPC" usage:"Maximum wait for RPC client operations" type:"duration" longdesc:"### Purpose\nTimeout for outbound RPC client calls when the RPC service acts as a client to other Teranode services.\n\n### How It Works\nApplies to calls to backend services including Blockchain service (getblock, getblockheader), Block Assembly (getminingcandidate), Validator (sendrawtransaction), and P2P (getpeerinfo, setban). Distinct from rpc_timeout which applies to inbound RPC requests from clients.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Longer | Tolerates slow backends | Slower failure detection |\n| Shorter | Faster failure detection | May timeout during high load |\n\n### Recommendations\n- **5s** (default) - Sufficient for most inter-service gRPC calls within the same datacenter\n- Increase when backend services are slow (overloaded)\n- Increase for high network latency (multi-region deployments)\n- Decrease for stricter responsiveness requirements"`
}
